/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced for configurator functionality
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce
Title: McLaren F1 1993 By Alex.Ka.🤍🖤
*/

"use client";

import * as THREE from "three";
import React, { useRef, useMemo, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeEvent } from "@react-three/fiber";
import { gsap } from "gsap";

// ============================================
// TYPE DEFINITIONS
// ============================================

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
  };
  materials: {
    F1_front_plastic: THREE.MeshPhysicalMaterial;
    F1_nip_logo: THREE.MeshPhysicalMaterial;
    F1_red_F: THREE.MeshPhysicalMaterial;
    F1_red_R: THREE.MeshStandardMaterial;
    F1_side: THREE.MeshPhysicalMaterial;
    McLAREN_RED_LINE: THREE.MeshPhysicalMaterial;
    McLAREN_sidelogo: THREE.MeshPhysicalMaterial;
    McLAREN_sidelogo_FBUMPER: THREE.MeshPhysicalMaterial;
    McLaren_F1_1993_By_Alex_Ka: THREE.MeshPhysicalMaterial;
    McLaren_logo: THREE.MeshPhysicalMaterial;
    McLaren_supportlogo: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    black_aluminium: THREE.MeshStandardMaterial;
    black_chrome: THREE.MeshStandardMaterial;
    black_chrome2: THREE.MeshPhysicalMaterial;
    black_matte: THREE.MeshStandardMaterial;
    black_plastic: THREE.MeshPhysicalMaterial;
    bottom: THREE.MeshStandardMaterial;
    brakedisk: THREE.MeshStandardMaterial;
    brakelight: THREE.MeshPhysicalMaterial;
    bronze: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    chrome2: THREE.MeshStandardMaterial;
    door_stitch: THREE.MeshStandardMaterial;
    engine: THREE.MeshStandardMaterial;
    exhaust: THREE.MeshStandardMaterial;
    exhaust_gold: THREE.MeshStandardMaterial;
    exhaust_hole: THREE.MeshStandardMaterial;
    exhaust_metal_circles: THREE.MeshPhysicalMaterial;
    floor: THREE.MeshPhysicalMaterial;
    front_turn_signal: THREE.MeshPhysicalMaterial;
    fuel_clap: THREE.MeshPhysicalMaterial;
    grill1: THREE.MeshStandardMaterial;
    grill2: THREE.MeshStandardMaterial;
    grill_3: THREE.MeshStandardMaterial;
    grill_f: THREE.MeshStandardMaterial;
    grill_side: THREE.MeshStandardMaterial;
    headlight_1: THREE.MeshPhysicalMaterial;
    headlight_2: THREE.MeshStandardMaterial;
    headlightglass: THREE.MeshPhysicalMaterial;
    interior: THREE.MeshStandardMaterial;
    mirrors: THREE.MeshStandardMaterial;
    material_42: THREE.MeshStandardMaterial;
    material_43: THREE.MeshPhysicalMaterial;
    plate_F: THREE.MeshPhysicalMaterial;
    plate_R: THREE.MeshPhysicalMaterial;
    rear_lamp: THREE.MeshPhysicalMaterial;
    rear_turn_signal: THREE.MeshPhysicalMaterial;
    material_48: THREE.MeshStandardMaterial;
    rimbolt: THREE.MeshStandardMaterial;
    rimlogo: THREE.MeshPhysicalMaterial;
    side_turn_signal: THREE.MeshPhysicalMaterial;
    suport: THREE.MeshPhysicalMaterial;
    tire: THREE.MeshStandardMaterial;
    tire_side: THREE.MeshStandardMaterial;
    windo_F: THREE.MeshPhysicalMaterial;
    windo_R: THREE.MeshPhysicalMaterial;
    windo_S: THREE.MeshPhysicalMaterial;
  };
};

// Part group identifiers for the configurator
export type CarPart =
  | "body"
  | "accents"
  | "wheels"
  | "interior"
  | "windows"
  | "lights"
  | "chrome"
  | "engine";

export interface CarColors {
  body: string;
  accents: string;
  wheels: string;
  interior: string;
  windows: string;
  chrome: string;
}

export interface CarModelProps {
  colors?: Partial<CarColors>;
  selectedPart?: CarPart | null;
  onPartClick?: (part: CarPart) => void;
  onPartHover?: (part: CarPart | null) => void;
}

// Default colors for the car
const defaultColors: CarColors = {
  body: "#1a1a2e",
  accents: "#dc2626",
  wheels: "#18181b",
  interior: "#8B4513",
  windows: "#1a1a2e",
  chrome: "#C0C0C0",
};

// ============================================
// MAIN COMPONENT
// ============================================

export function CarModel({
  colors = {},
  onPartClick,
  onPartHover,
}: CarModelProps) {
  const groupRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/models/car.glb") as GLTFResult;

  // Merge provided colors with defaults
  const activeColors = useMemo(
    () => ({ ...defaultColors, ...colors }),
    [colors]
  );

  // Create custom materials based on colors
  const customMaterials = useMemo(() => {
    return {
      // Body materials
      body: new THREE.MeshPhysicalMaterial({
        color: activeColors.body,
        metalness: 0.8,
        roughness: 0.2,
        clearcoat: 1,
        clearcoatRoughness: 0.1,
      }),
      // Accent materials (stripes, logos)
      accent: new THREE.MeshPhysicalMaterial({
        color: activeColors.accents,
        metalness: 0.6,
        roughness: 0.3,
      }),
      // Wheel materials
      wheels: new THREE.MeshStandardMaterial({
        color: activeColors.wheels,
        metalness: 0.9,
        roughness: 0.3,
      }),
      // Interior materials
      interior: new THREE.MeshStandardMaterial({
        color: activeColors.interior,
        metalness: 0.1,
        roughness: 0.8,
      }),
      // Window materials (tinted glass)
      windows: new THREE.MeshPhysicalMaterial({
        color: activeColors.windows,
        metalness: 0,
        roughness: 0,
        transmission: 0.9,
        transparent: true,
        opacity: 0.3,
      }),
      // Chrome materials
      chrome: new THREE.MeshStandardMaterial({
        color: activeColors.chrome,
        metalness: 1,
        roughness: 0.1,
      }),
    };
  }, [activeColors]);

  // GSAP entrance animation
  useEffect(() => {
    if (groupRef.current) {
      gsap.fromTo(
        groupRef.current.rotation,
        { y: -Math.PI / 4 },
        { y: 0, duration: 1.5, ease: "power3.out" }
      );
      gsap.fromTo(
        groupRef.current.position,
        { y: -2 },
        { y: 0, duration: 1.2, ease: "power3.out" }
      );
    }
  }, []);

  // Handle click on parts
  const handleClick = (part: CarPart) => (e: ThreeEvent<MouseEvent>) => {
    e.stopPropagation();
    onPartClick?.(part);
  };

  // Handle hover on parts
  const handlePointerOver = (part: CarPart) => (e: ThreeEvent<PointerEvent>) => {
    e.stopPropagation();
    document.body.style.cursor = "pointer";
    onPartHover?.(part);
  };

  const handlePointerOut = () => {
    document.body.style.cursor = "auto";
    onPartHover?.(null);
  };

  return (
    <group ref={groupRef} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      >
        {/* ==================== BODY PARTS ==================== */}
        <group
          onClick={handleClick("body")}
          onPointerOver={handlePointerOver("body")}
          onPointerOut={handlePointerOut}
        >
          {/* Main body */}
          <mesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={customMaterials.body}
          />
          {/* Side panels */}
          <mesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={customMaterials.body}
          />
          {/* Front plastic */}
          <mesh
            name="Object_2"
            geometry={nodes.Object_2.geometry}
            material={customMaterials.body}
          />
          {/* Fuel cap */}
          <mesh
            name="Object_33"
            geometry={nodes.Object_33.geometry}
            material={customMaterials.body}
          />
        </group>

        {/* ==================== ACCENT PARTS ==================== */}
        <group
          onClick={handleClick("accents")}
          onPointerOver={handlePointerOver("accents")}
          onPointerOut={handlePointerOut}
        >
          {/* Red lines/stripes */}
          <mesh
            name="Object_7"
            geometry={nodes.Object_7.geometry}
            material={customMaterials.accent}
          />
          {/* Front red accent */}
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={customMaterials.accent}
          />
          {/* Rear red accent */}
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={customMaterials.accent}
          />
        </group>

        {/* ==================== WHEELS ==================== */}
        <group
          onClick={handleClick("wheels")}
          onPointerOver={handlePointerOver("wheels")}
          onPointerOut={handlePointerOut}
        >
          {/* Tires */}
          <mesh
            name="Object_55"
            geometry={nodes.Object_55.geometry}
            material={materials.tire}
          />
          <mesh
            name="Object_56"
            geometry={nodes.Object_56.geometry}
            material={materials.tire_side}
          />
          {/* Rim bolts */}
          <mesh
            name="Object_51"
            geometry={nodes.Object_51.geometry}
            material={customMaterials.wheels}
          />
          {/* Rim logos */}
          <mesh
            name="Object_52"
            geometry={nodes.Object_52.geometry}
            material={customMaterials.wheels}
          />
          {/* Brake disks */}
          <mesh
            name="Object_20"
            geometry={nodes.Object_20.geometry}
            material={materials.brakedisk}
          />
        </group>

        {/* ==================== INTERIOR ==================== */}
        <group
          onClick={handleClick("interior")}
          onPointerOver={handlePointerOver("interior")}
          onPointerOut={handlePointerOut}
        >
          <mesh
            name="Object_42"
            geometry={nodes.Object_42.geometry}
            material={customMaterials.interior}
          />
          <mesh
            name="Object_25"
            geometry={nodes.Object_25.geometry}
            material={customMaterials.interior}
          />
          <mesh
            name="Object_31"
            geometry={nodes.Object_31.geometry}
            material={materials.floor}
          />
        </group>

        {/* ==================== WINDOWS ==================== */}
        <group
          onClick={handleClick("windows")}
          onPointerOver={handlePointerOver("windows")}
          onPointerOut={handlePointerOut}
        >
          <mesh
            name="Object_57"
            geometry={nodes.Object_57.geometry}
            material={customMaterials.windows}
          />
          <mesh
            name="Object_58"
            geometry={nodes.Object_58.geometry}
            material={customMaterials.windows}
          />
          <mesh
            name="Object_59"
            geometry={nodes.Object_59.geometry}
            material={customMaterials.windows}
          />
        </group>

        {/* ==================== CHROME PARTS ==================== */}
        <group
          onClick={handleClick("chrome")}
          onPointerOver={handlePointerOver("chrome")}
          onPointerOut={handlePointerOut}
        >
          <mesh
            name="Object_23"
            geometry={nodes.Object_23.geometry}
            material={customMaterials.chrome}
          />
          <mesh
            name="Object_24"
            geometry={nodes.Object_24.geometry}
            material={customMaterials.chrome}
          />
          <mesh
            name="Object_43"
            geometry={nodes.Object_43.geometry}
            material={customMaterials.chrome}
          />
        </group>

        {/* ==================== LIGHTS ==================== */}
        <group
          onClick={handleClick("lights")}
          onPointerOver={handlePointerOver("lights")}
          onPointerOut={handlePointerOut}
        >
          <mesh
            name="Object_39"
            geometry={nodes.Object_39.geometry}
            material={materials.headlight_1}
          />
          <mesh
            name="Object_40"
            geometry={nodes.Object_40.geometry}
            material={materials.headlight_2}
          />
          <mesh
            name="Object_41"
            geometry={nodes.Object_41.geometry}
            material={materials.headlightglass}
          />
          <mesh
            name="Object_21"
            geometry={nodes.Object_21.geometry}
            material={materials.brakelight}
          />
          <mesh
            name="Object_48"
            geometry={nodes.Object_48.geometry}
            material={materials.rear_lamp}
          />
          <mesh
            name="Object_32"
            geometry={nodes.Object_32.geometry}
            material={materials.front_turn_signal}
          />
          <mesh
            name="Object_49"
            geometry={nodes.Object_49.geometry}
            material={materials.rear_turn_signal}
          />
          <mesh
            name="Object_53"
            geometry={nodes.Object_53.geometry}
            material={materials.side_turn_signal}
          />
        </group>

        {/* ==================== ENGINE ==================== */}
        <group
          onClick={handleClick("engine")}
          onPointerOver={handlePointerOver("engine")}
          onPointerOut={handlePointerOut}
        >
          <mesh
            name="Object_26"
            geometry={nodes.Object_26.geometry}
            material={materials.engine}
          />
          <mesh
            name="Object_27"
            geometry={nodes.Object_27.geometry}
            material={materials.exhaust}
          />
          <mesh
            name="Object_28"
            geometry={nodes.Object_28.geometry}
            material={materials.exhaust_gold}
          />
          <mesh
            name="Object_29"
            geometry={nodes.Object_29.geometry}
            material={materials.exhaust_hole}
          />
          <mesh
            name="Object_30"
            geometry={nodes.Object_30.geometry}
            material={materials.exhaust_metal_circles}
          />
        </group>

        {/* ==================== OTHER PARTS (non-configurable) ==================== */}
        {/* Logos */}
        <mesh
          name="Object_3"
          geometry={nodes.Object_3.geometry}
          material={materials.F1_nip_logo}
        />
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.McLAREN_sidelogo}
        />
        <mesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.McLAREN_sidelogo_FBUMPER}
        />
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.McLaren_logo}
        />
        <mesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.McLaren_supportlogo}
        />

        {/* Black/structural parts */}
        <mesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials.black_aluminium}
        />
        <mesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials.black_chrome}
        />
        <mesh
          name="Object_16"
          geometry={nodes.Object_16.geometry}
          material={materials.black_chrome2}
        />
        <mesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.black_matte}
        />
        <mesh
          name="Object_18"
          geometry={nodes.Object_18.geometry}
          material={materials.black_plastic}
        />
        <mesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials.bottom}
        />
        <mesh
          name="Object_22"
          geometry={nodes.Object_22.geometry}
          material={materials.bronze}
        />

        {/* Grills */}
        <mesh
          name="Object_34"
          geometry={nodes.Object_34.geometry}
          material={materials.grill1}
        />
        <mesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials.grill2}
        />
        <mesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials.grill_3}
        />
        <mesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials.grill_f}
        />
        <mesh
          name="Object_38"
          geometry={nodes.Object_38.geometry}
          material={materials.grill_side}
        />

        {/* Plates and misc */}
        <mesh
          name="Object_44"
          geometry={nodes.Object_44.geometry}
          material={materials.material_42}
        />
        <mesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.material_43}
        />
        <mesh
          name="Object_46"
          geometry={nodes.Object_46.geometry}
          material={materials.plate_F}
        />
        <mesh
          name="Object_47"
          geometry={nodes.Object_47.geometry}
          material={materials.plate_R}
        />
        <mesh
          name="Object_50"
          geometry={nodes.Object_50.geometry}
          material={materials.material_48}
        />
        <mesh
          name="Object_54"
          geometry={nodes.Object_54.geometry}
          material={materials.suport}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/car.glb");

export default CarModel;
